# Generated by Django 6.0.4 on 2026-04-13 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('phone', 'Phone'), ('keys', 'Keys'), ('documents', 'Documents'), ('backpack', 'Backpack'), ('clothes', 'Clothes'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='lost', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
